export const commands = [
  {
    category: "Masaüstü",
    command: "Hesap makinesini aç.",
    result: "Windows hesap makinesini açar.",
    requirement: "Uygulama bilgisayarında kurulu olmalı.",
    anchor: "uygulamalar",
  },
  {
    category: "Masaüstü",
    command: "Çalışan uygulamaları göster.",
    result: "Çalışan uygulamaları listeler.",
    requirement: "Windows masaüstü oturumu.",
    anchor: "uygulamalar",
  },
  {
    category: "Web",
    command: "Web'de Python dokümantasyonunu ara.",
    result: "Aramayı tarayıcında açar.",
    requirement: "İnternet bağlantısı ve varsayılan tarayıcı.",
    anchor: "uygulamalar",
  },
  {
    category: "Dosyalar",
    command: "İndirilenler klasörünü listele.",
    result: "Klasörün içeriğini gösterir.",
    requirement: "Klasöre erişim izni.",
    anchor: "dosyalar",
  },
  {
    category: "Dosyalar",
    command: "rapor.pdf dosyasını bul.",
    result: "Dosya adına göre eşleşen yolları arar.",
    requirement: "Aranacak dosya mevcut olmalı. Gerekirse klasör yolunu belirt.",
    anchor: "dosyalar",
  },
  {
    category: "Dosyalar",
    command: "Masaüstünde Proje Notları adlı bir klasör oluştur.",
    result: "Belirttiğin isimle yeni bir klasör oluşturur.",
    requirement: "Hedef konumda yazma izni.",
    anchor: "dosyalar",
  },
  {
    category: "Notlar",
    command: "Bir not al: tasarım için açık yeşil vurgu kullan.",
    result: "Düşünceni notlar arasına kaydeder.",
    requirement: "Jarvis’in yerel veri dizinine yazma izni.",
    anchor: "notlar",
  },
  {
    category: "Notlar",
    command: "Tasarım hakkındaki notlarımı bul.",
    result: "Kaydedilmiş notlarında arama yapar.",
    requirement: "Daha önce kaydedilmiş notlar.",
    anchor: "notlar",
  },
  {
    category: "Notlar",
    command: "10 dakika sonra mola vermemi hatırlat.",
    result: "Belirtilen süre için hatırlatıcı oluşturur.",
    requirement: "Hatırlatma sırasında Jarvis açık kalmalı.",
    anchor: "notlar",
  },
  {
    category: "Ekran",
    command: "Ekrandaki hata mesajını açıkla.",
    result: "Ekran görüntüsündeki hatayı yorumlar.",
    requirement: "Gemini API bağlantısı. Ekran görüntüsü dış sağlayıcıya gönderilir.",
    anchor: "ekran",
  },
];
