import fs from "node:fs";
import path from "node:path";
const directory = path.resolve("src/content/docs");
const metadata = JSON.parse(fs.readFileSync(path.join(directory, "meta.json"), "utf8"));
const docs = fs
  .readdirSync(directory)
  .filter((file) => file.endsWith(".mdx"))
  .map((file) => {
    const text = fs.readFileSync(path.join(directory, file), "utf8");
    const doc = metadata.find((item) => `${item.slug}.mdx` === file);
    if (!doc) throw new Error(`Missing metadata: ${file}`);
    if (
      !/^\d{4}-\d{2}-\d{2}$/.test(doc.updatedAt || "") ||
      !Number.isFinite(Date.parse(doc.updatedAt)) ||
      new Date(doc.updatedAt).toISOString().slice(0, 10) !== doc.updatedAt
    )
      throw new Error(`Invalid editorial date: ${file}`);
    if (file !== `${doc.slug}.mdx` || !/^[a-z0-9-]+$/.test(doc.slug))
      throw new Error(`Invalid slug: ${file}`);
    const sections = [
      ...text.matchAll(/<section className="doc-section" id="([^"]+)">([\s\S]*?)<\/section>/g),
    ].map(([, id, content]) => {
      const title = content.match(/^## (.+)$/m)?.[1];
      if (!title) throw new Error(`Missing heading in ${file}#${id}`);
      const plain = content
        .replace(/<CopyCode\s+code=\{("(?:[^"\\]|\\.)*")\}[^>]*\/>/g, (_, code) => JSON.parse(code))
        .replace(/<[^>]+>/g, " ")
        .replace(/^## .+$/m, "")
        .trim();
      return { id, title, body: [plain] };
    });
    if (!sections.length || new Set(sections.map((s) => s.id)).size !== sections.length)
      throw new Error(`Invalid sections: ${file}`);
    return { ...doc, sections };
  })
  .sort((a, b) => a.order - b.order);
fs.writeFileSync("src/lib/docs-index.json", JSON.stringify(docs, null, 2) + "\n");
fs.writeFileSync(
  path.join(directory, "registry.ts"),
  '// Generated by npm run docs:index.\nimport type { ComponentType } from "react";\n' +
    docs.map((doc, i) => `import Doc${i} from "./${doc.slug}.mdx";`).join("\n") +
    "\nexport const docContent: Record<string, ComponentType> = {\n" +
    docs.map((doc, i) => `  "${doc.slug}": Doc${i},`).join("\n") +
    "\n};\n",
);
console.log(`Indexed ${docs.length} MDX documents.`);
