// Generated by npm run docs:index.
import type { ComponentType } from "react";
import Doc0 from "./baslangic.mdx";
import Doc1 from "./kurulum.mdx";
import Doc2 from "./saglayicilar.mdx";
import Doc3 from "./sesli-kullanim.mdx";
import Doc4 from "./komutlar.mdx";
import Doc5 from "./gizlilik.mdx";
import Doc6 from "./sorun-giderme.mdx";
import Doc7 from "./guncellemeler.mdx";
export const docContent: Record<string, ComponentType> = {
  "baslangic": Doc0,
  "kurulum": Doc1,
  "saglayicilar": Doc2,
  "sesli-kullanim": Doc3,
  "komutlar": Doc4,
  "gizlilik": Doc5,
  "sorun-giderme": Doc6,
  "guncellemeler": Doc7,
};
